import { Injectable, Logger } from '@nestjs/common';
import { Cron, CronExpression } from '@nestjs/schedule';
import { PrismaService } from '../../prisma/prisma.service';
import { PostizService } from '../postiz/postiz.service';
import { ActionLogService } from '../action-log/action-log.service';

/**
 * ContentSchedulerService — runs every 2 minutes.
 *
 * Finds ContentDrafts with status=APPROVED that were generated by the
 * automation pipeline (identified by pageProfileId in metadata) and
 * schedules them to Postiz, then creates a ContentArchive entry.
 */
@Injectable()
export class ContentSchedulerService {
  private readonly logger = new Logger(ContentSchedulerService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly postizService: PostizService,
    private readonly actionLogService: ActionLogService,
  ) {}

  @Cron('*/2 * * * *') // Every 2 minutes
  async scheduleApprovedDrafts(): Promise<void> {
    const approvedDrafts = await this.prisma.contentDraft.findMany({
      where: { status: 'APPROVED' },
    });

    const automationDrafts = approvedDrafts.filter((d) => {
      const meta = d.metadata as any;
      return meta?.pageProfileId;
    });

    if (automationDrafts.length === 0) return;

    this.logger.log(`Found ${automationDrafts.length} approved draft(s) to schedule`);

    for (const draft of automationDrafts) {
      await this.scheduleDraft(draft);
    }
  }

  private async scheduleDraft(draft: any): Promise<void> {
    const meta = draft.metadata as any;
    const pageProfileId: string = meta.pageProfileId;

    try {
      // Fetch PageProfile for schedule config + social connections
      const pageProfile = await this.prisma.pageProfile.findUnique({
        where: { id: pageProfileId },
      });

      if (!pageProfile || pageProfile.status !== 'ACTIVE') {
        this.logger.warn(`PageProfile ${pageProfileId} not found or inactive — skipping`, {
          draftId: draft.id,
        });
        await this.markFailed(draft, 'PageProfile not found or inactive');
        return;
      }

      const socialConnectionIds: string[] = pageProfile.socialConnectionIds;
      if (socialConnectionIds.length === 0) {
        this.logger.warn(`PageProfile ${pageProfileId} has no social connections`, {
          draftId: draft.id,
        });
        await this.markFailed(draft, 'No social connections configured');
        return;
      }

      // Fetch SocialConnections to get Postiz integration IDs
      const socialConnections = await this.prisma.socialConnection.findMany({
        where: {
          id: { in: socialConnectionIds },
          status: 'ACTIVE',
        },
      });

      if (socialConnections.length === 0) {
        await this.markFailed(draft, 'No active social connections found');
        return;
      }

      const integrationIds = socialConnections.map((sc) => sc.postizIntegrationId);

      // Calculate schedule time: next slot from PageProfile.schedule
      const scheduledAt = this.calculateNextScheduleTime(pageProfile.schedule as any);

      // Build hashtag suffix for body
      const hashtags: string[] = meta.hashtags || [];
      const hashtagSuffix =
        hashtags.length > 0 ? '\n\n' + hashtags.map((h: string) => `#${h}`).join(' ') : '';
      const fullBody = draft.body + hashtagSuffix;

      // Call Postiz to schedule
      const postizResponse = await this.postizService.schedulePost({
        integrationIds,
        content: fullBody,
        scheduledAt: scheduledAt.toISOString(),
      });

      // Update draft status to SCHEDULED
      await this.prisma.contentDraft.update({
        where: { id: draft.id },
        data: {
          status: 'SCHEDULED',
          scheduledAt,
          metadata: {
            ...meta,
            postizPostId: postizResponse?.id,
          },
        },
      });

      // Create PublishTarget entries per social connection
      await Promise.all(
        socialConnections.map((sc) =>
          this.prisma.publishTarget.create({
            data: {
              contentDraftId: draft.id,
              socialConnectionId: sc.id,
              postizPostId: postizResponse?.id,
              status: 'SCHEDULED',
              scheduledAt,
            },
          }),
        ),
      );

      // Create ContentArchive entry
      await this.prisma.contentArchive.create({
        data: {
          pageProfileId,
          contentDraftId: draft.id,
          body: draft.body,
          hashtags: meta.hashtags || [],
          mediaUrls: [],
          generatedBy: meta.generatedBy || 'ai-original',
          sourceUrl: meta.sourceUrl || null,
          generationModel: meta.generationModel || null,
          qaScore: this.extractQAScore(meta),
          qaAttempts: meta.qaAttempts || 1,
          qaAgentResults: meta.qaResults || null,
          platforms: socialConnections.map((sc) => sc.provider.toLowerCase()),
        },
      });

      // Log action
      await this.actionLogService.log({
        workspaceId: draft.workspaceId,
        actorId: 'system',
        action: 'CONTENT_SCHEDULED',
        resourceType: 'ContentDraft',
        resourceId: draft.id,
        payload: { pageProfileId, scheduledAt: scheduledAt.toISOString(), integrationIds },
        outcome: 'SUCCESS',
      });

      this.logger.log(`Draft ${draft.id} scheduled for ${scheduledAt.toISOString()}`, {
        pageProfileId,
        integrationIds,
      });
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      this.logger.error(`Failed to schedule draft ${draft.id}`, { error: errorMessage });
      await this.markFailed(draft, errorMessage);

      await this.actionLogService.log({
        workspaceId: draft.workspaceId,
        actorId: 'system',
        action: 'CONTENT_SCHEDULE_FAILED',
        resourceType: 'ContentDraft',
        resourceId: draft.id,
        payload: { pageProfileId, error: errorMessage },
        outcome: 'FAILURE',
        level: 'ERROR',
      });
    }
  }

  private async markFailed(draft: any, reason: string): Promise<void> {
    await this.prisma.contentDraft.update({
      where: { id: draft.id },
      data: {
        status: 'FAILED',
        metadata: { ...(draft.metadata as any), scheduleError: reason },
      },
    });
  }

  /**
   * Find the next upcoming time slot from the PageProfile schedule.
   * Falls back to 10 minutes from now if no schedule times are configured.
   */
  private calculateNextScheduleTime(schedule: any): Date {
    const now = new Date();
    const timezone: string = schedule?.timezone || 'Asia/Ho_Chi_Minh';
    const times: string[] = schedule?.times || [];

    if (times.length === 0) {
      // Default: 10 minutes from now
      return new Date(now.getTime() + 10 * 60 * 1000);
    }

    // Find next upcoming slot today or tomorrow
    const todayStr = now.toLocaleDateString('en-CA', { timeZone: timezone }); // YYYY-MM-DD

    const candidates: Date[] = [];
    for (const time of times) {
      const [hourStr, minStr] = time.split(':');
      const hour = parseInt(hourStr ?? '9', 10);
      const min = parseInt(minStr ?? '0', 10);

      // Build a date in local timezone
      const candidate = new Date(`${todayStr}T${String(hour).padStart(2, '0')}:${String(min).padStart(2, '0')}:00`);

      // If slot is in the past, shift to tomorrow
      if (candidate.getTime() <= now.getTime() + 5 * 60 * 1000) {
        candidate.setDate(candidate.getDate() + 1);
      }

      candidates.push(candidate);
    }

    candidates.sort((a, b) => a.getTime() - b.getTime());
    return candidates[0] ?? new Date(now.getTime() + 10 * 60 * 1000);
  }

  private extractQAScore(meta: any): number {
    const qa = meta?.qaResults;
    if (!qa) return 0;
    const scores = [qa.quality?.score, qa.brandVoice?.score].filter(
      (s): s is number => typeof s === 'number',
    );
    if (scores.length === 0) return 0;
    return scores.reduce((a, b) => a + b, 0) / scores.length;
  }
}
